//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIIU4
    {
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public string CodigoCIIU { get; set; }
        public string DescripcionCIIU { get; set; }
    }
}
