//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategoria2Cabys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategoria2Cabys()
        {
            this.tbCategoria3Cabys = new HashSet<tbCategoria3Cabys>();
        }
    
        public string idCategoria1 { get; set; }
        public string idCategoria2 { get; set; }
        public string nombre { get; set; }
    
        public virtual tbCategoria1Cabys tbCategoria1Cabys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCategoria3Cabys> tbCategoria3Cabys { get; set; }
    }
}
