//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCajasMovimientos
    {
        public int id { get; set; }
        public System.DateTime fechaApertura { get; set; }
        public decimal montoApertura { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<decimal> montoCierre { get; set; }
        public string usuarioApertura { get; set; }
        public string usuarioCierre { get; set; }
        public int caja { get; set; }
        public int sucursal { get; set; }
    }
}
