//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategoria3Cabys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategoria3Cabys()
        {
            this.tbCategoria4Cabys = new HashSet<tbCategoria4Cabys>();
        }
    
        public string idCategoria1 { get; set; }
        public string idCategoria2 { get; set; }
        public string idCategoria3 { get; set; }
        public string nombre { get; set; }
    
        public virtual tbCategoria2Cabys tbCategoria2Cabys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCategoria4Cabys> tbCategoria4Cabys { get; set; }
    }
}
