//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategoria6Cabys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategoria6Cabys()
        {
            this.tbCategoria7Cabys = new HashSet<tbCategoria7Cabys>();
        }
    
        public string idCategoria1 { get; set; }
        public string idCategoria2 { get; set; }
        public string idCategoria3 { get; set; }
        public string idCategoria4 { get; set; }
        public string idCategoria5 { get; set; }
        public string idCategoria6 { get; set; }
        public string nombre { get; set; }
    
        public virtual tbCategoria5Cabys tbCategoria5Cabys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCategoria7Cabys> tbCategoria7Cabys { get; set; }
    }
}
