//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbChoferes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbChoferes()
        {
            this.tbServicios = new HashSet<tbServicios>();
        }
    
        public string id { get; set; }
        public int tipoId { get; set; }
        public bool licVigente { get; set; }
        public int tipoLicencia { get; set; }
        public bool estado { get; set; }
        public string idEmpresa { get; set; }
        public int tipoIdEmpresa { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaUltModi { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioUltModi { get; set; }
        public Nullable<System.DateTime> fechaHoraAprob { get; set; }
        public Nullable<bool> condicion { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechaExpedicion { get; set; }
        public Nullable<System.DateTime> fechaExpiracion { get; set; }
    
        public virtual tbEmpresas tbEmpresas { get; set; }
        public virtual tbPersonas tbPersonas { get; set; }
        public virtual tbTipoLicencias tbTipoLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios { get; set; }
    }
}
