//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClienteActividad
    {
        public string idCliente { get; set; }
        public int tipoIdCliente { get; set; }
        public string codigoActividad { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_crea { get; set; }
    
        public virtual tbActividades tbActividades { get; set; }
        public virtual tbClientes tbClientes { get; set; }
    }
}
