//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleOrdenCompra
    {
        public int idDetalle { get; set; }
        public int idOrdenCompra { get; set; }
        public int numLinea { get; set; }
        public string idProducto { get; set; }
        public int idMedida { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioCosto { get; set; }
    
        public virtual tbOrdenCompra tbOrdenCompra { get; set; }
        public virtual tbProducto tbProducto { get; set; }
        public virtual tbTipoMedidas tbTipoMedidas { get; set; }
    }
}
