//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleCompras
    {
        public int idDetalle { get; set; }
        public int idCompra { get; set; }
        public int TipoCompra { get; set; }
        public int numLinea { get; set; }
        public string idProducto { get; set; }
        public string nombreProducto { get; set; }
        public int idMedida { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public decimal montoTotal { get; set; }
        public decimal montoTotaDesc { get; set; }
        public decimal montoTotalImp { get; set; }
        public decimal montoTotalExo { get; set; }
        public decimal montoTotalLinea { get; set; }
        public bool actualizaPrecio { get; set; }
        public bool actualizaInvent { get; set; }
        public Nullable<decimal> utilidad { get; set; }
        public string codigoCabys { get; set; }
        public decimal tarifaImp { get; set; }
        public string idProductoProveedor { get; set; }
        public string nomenclatura { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> idMedidaVenta { get; set; }
        public Nullable<decimal> cantidadVenta { get; set; }
        public Nullable<decimal> tarifaImpVenta { get; set; }
        public Nullable<decimal> montoOtroImp { get; set; }
    
        public virtual tbCompras tbCompras { get; set; }
        public virtual tbTipoMedidas tbTipoMedidas { get; set; }
    }
}
