//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDistritos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDistritos()
        {
            this.tbServicios = new HashSet<tbServicios>();
            this.tbServicios1 = new HashSet<tbServicios>();
        }
    
        public int provinciaId { get; set; }
        public int cantonId { get; set; }
        public int idDistrito { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaUltModi { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioUltModi { get; set; }
    
        public virtual tbCantones tbCantones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios1 { get; set; }
    }
}
