//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpresaActividades
    {
        public string idEmpresa { get; set; }
        public int tipoId { get; set; }
        public string CodActividad { get; set; }
        public string correoElectronicoEmpresa { get; set; }
        public string contrasenaCorreo { get; set; }
        public string cuerpoCorreo { get; set; }
        public string subjectCorreo { get; set; }
        public Nullable<bool> regimenSimplificado { get; set; }
        public Nullable<int> tipoFacturacionRegimen { get; set; }
        public string nombreComercial { get; set; }
        public Nullable<bool> principal { get; set; }
        public string correoCompras { get; set; }
        public string claveCorreo { get; set; }
    
        public virtual tbActividades tbActividades { get; set; }
        public virtual tbEmpresa tbEmpresa { get; set; }
    }
}
