//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEmpresa()
        {
            this.tbDocumento = new HashSet<tbDocumento>();
            this.tbEmpresaActividades = new HashSet<tbEmpresaActividades>();
            this.tbOrdenCompra = new HashSet<tbOrdenCompra>();
            this.tbParametrosEmpresa = new HashSet<tbParametrosEmpresa>();
            this.tbReporteHacienda = new HashSet<tbReporteHacienda>();
            this.tbUsuarios = new HashSet<tbUsuarios>();
        }
    
        public string id { get; set; }
        public int tipoId { get; set; }
        public string razonSocial { get; set; }
        public string certificadoInstalado { get; set; }
        public string rutaCertificado { get; set; }
        public Nullable<int> pin { get; set; }
        public string usuarioApiHacienda { get; set; }
        public string claveApiHacienda { get; set; }
        public string numeroResolucion { get; set; }
        public Nullable<System.DateTime> fechaResolucio { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
        public Nullable<bool> ambientePruebas { get; set; }
        public string rutaXMLCompras { get; set; }
        public Nullable<bool> imprimeDoc { get; set; }
        public string nombreImpresora { get; set; }
        public bool regimenSimplificado { get; set; }
        public Nullable<int> tipoFacturacionRegimen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumento> tbDocumento { get; set; }
        public virtual tbPersona tbPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpresaActividades> tbEmpresaActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOrdenCompra> tbOrdenCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbParametrosEmpresa> tbParametrosEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReporteHacienda> tbReporteHacienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}
