//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleado
    {
        public string id { get; set; }
        public int tipoId { get; set; }
        public int idPuesto { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_crea { get; set; }
        public bool esContraDefinido { get; set; }
        public string direccion { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbTipoPuesto tbTipoPuesto { get; set; }
    }
}
