//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMovimientos
    {
        public int idMovimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public int idTipoMov { get; set; }
        public bool estado { get; set; }
        public string motivo { get; set; }
        public decimal total { get; set; }
        public Nullable<int> caja { get; set; }
        public Nullable<int> sucursal { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_mod { get; set; }
    
        public virtual tbTipoMovimiento tbTipoMovimiento { get; set; }
    }
}
