//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrdenCompra()
        {
            this.tbDetalleOrdenCompra = new HashSet<tbDetalleOrdenCompra>();
        }
    
        public int id { get; set; }
        public string idProveedor { get; set; }
        public int tipoIdProveedor { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipoPago { get; set; }
        public Nullable<int> plazo { get; set; }
        public int estadoOrden { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechaRecibida { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_mod { get; set; }
        public bool estado { get; set; }
        public string idEmpresa { get; set; }
        public int tipoIdEmpresa { get; set; }
        public bool notificarCorreo { get; set; }
        public string correo1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleOrdenCompra> tbDetalleOrdenCompra { get; set; }
        public virtual tbEmpresa tbEmpresa { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
        public virtual tbTipoPago tbTipoPago { get; set; }
    }
}
