//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPagos
    {
        public int idAbono { get; set; }
        public int idDoc { get; set; }
        public int tipoDoc { get; set; }
        public Nullable<decimal> monto { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_mod { get; set; }
        public bool estado { get; set; }
        public string refPago { get; set; }
        public int tipoPago { get; set; }
        public Nullable<int> sucursal { get; set; }
        public Nullable<int> caja { get; set; }
    
        public virtual tbDocumento tbDocumento { get; set; }
        public virtual tbTipoPago tbTipoPago { get; set; }
    }
}
