//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersona
    {
        public int tipoId { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string correoElectronico { get; set; }
        public Nullable<System.DateTime> fechaNac { get; set; }
        public Nullable<int> sexo { get; set; }
        public string codigoPaisTel { get; set; }
        public int telefono { get; set; }
        public string codigoPaisFax { get; set; }
        public Nullable<int> fax { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string barrio { get; set; }
        public string otrasSenas { get; set; }
    
        public virtual tbBarrios tbBarrios { get; set; }
        public virtual tbClientes tbClientes { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbEmpresa tbEmpresa { get; set; }
        public virtual tbTipoId tbTipoId { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
    }
}
