//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPersonas()
        {
            this.tbUsuarios = new HashSet<tbUsuarios>();
        }
    
        public string id { get; set; }
        public int tipoId { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string genero { get; set; }
        public int celular { get; set; }
        public System.DateTime fechaNac { get; set; }
        public int codPostal { get; set; }
        public string direccion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaUltModi { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioUltModi { get; set; }
        public string correoElectronico { get; set; }
    
        public virtual tbChoferes tbChoferes { get; set; }
        public virtual tbClientes tbClientes { get; set; }
        public virtual tbEmpresas tbEmpresas { get; set; }
        public virtual tbTipoId tbTipoId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}
