//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPromociones
    {
        public int id { get; set; }
        public System.DateTime fechaIncio { get; set; }
        public System.DateTime fechaCierre { get; set; }
        public string idProducto { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_mod { get; set; }
        public decimal descuento { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public bool estado { get; set; }
    
        public virtual tbProducto tbProducto { get; set; }
    }
}
