//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbServicios
    {
        public int id { get; set; }
        public int tipoCarga { get; set; }
        public decimal peso { get; set; }
        public decimal ancho { get; set; }
        public string descripcion { get; set; }
        public string placa { get; set; }
        public int tipoPlaca { get; set; }
        public int estadoServicio { get; set; }
        public decimal alto { get; set; }
        public int distritoDestino { get; set; }
        public int cantonDestino { get; set; }
        public int provinciaDestino { get; set; }
        public int distritoOrigen { get; set; }
        public int cantonOrigen { get; set; }
        public int provinciaOrigen { get; set; }
        public string idCliente { get; set; }
        public int tipoIdCliente { get; set; }
        public string idChofer { get; set; }
        public int tipoIdChofer { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaUltModi { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioUltModi { get; set; }
    
        public virtual tbChoferes tbChoferes { get; set; }
        public virtual tbClientes tbClientes { get; set; }
        public virtual tbDistritos tbDistritos { get; set; }
        public virtual tbDistritos tbDistritos1 { get; set; }
        public virtual tbTipoCargas tbTipoCargas { get; set; }
        public virtual tbVehiculos tbVehiculos { get; set; }
    }
}
