//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        public int tipoId { get; set; }
        public string id { get; set; }
        public string nombreUsuario { get; set; }
        public string contraseña { get; set; }
        public int idRol { get; set; }
        public string foto_url { get; set; }
        public string idEmpresa { get; set; }
        public Nullable<int> idTipoIdEmpresa { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public System.DateTime fecha_ult_mod { get; set; }
        public string usuario_crea { get; set; }
        public string usuario_ult_mod { get; set; }
    
        public virtual tbEmpresa tbEmpresa { get; set; }
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbRoles tbRoles { get; set; }
    }
}
