//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbVehiculos()
        {
            this.tbServicios = new HashSet<tbServicios>();
        }
    
        public string placa { get; set; }
        public int tipoPlaca { get; set; }
        public int IdTipoVehiculo { get; set; }
        public int marca { get; set; }
        public int modelo { get; set; }
        public int IdTipoCombustible { get; set; }
        public bool rtv { get; set; }
        public bool marchamo { get; set; }
        public int seguro { get; set; }
        public bool estado { get; set; }
        public string cilindraje { get; set; }
        public string color { get; set; }
        public string IdEmpresa { get; set; }
        public int tipoIdEmpresa { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaUltModi { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioUltModi { get; set; }
        public Nullable<System.DateTime> fechaHoraAprob { get; set; }
        public Nullable<bool> condicion { get; set; }
        public string observaciones { get; set; }
    
        public virtual tbEmpresas tbEmpresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbServicios> tbServicios { get; set; }
        public virtual tbTipoCombustibles tbTipoCombustibles { get; set; }
        public virtual tbTipoVehiculos tbTipoVehiculos { get; set; }
    }
}
