//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using CommonLayer;
    using EntityLayer;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base(Global.conexion)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbAcompanamiento> tbAcompanamiento { get; set; }
        public virtual DbSet<tbActividades> tbActividades { get; set; }
        public virtual DbSet<tbBarrios> tbBarrios { get; set; }
        public virtual DbSet<tbCajasMovimientos> tbCajasMovimientos { get; set; }
        public virtual DbSet<tbCanton> tbCanton { get; set; }
        public virtual DbSet<tbCategoria1Cabys> tbCategoria1Cabys { get; set; }
        public virtual DbSet<tbCategoria7Cabys> tbCategoria7Cabys { get; set; }
        public virtual DbSet<tbCategoria8Cabys> tbCategoria8Cabys { get; set; }
        public virtual DbSet<tbCategoria9Cabys> tbCategoria9Cabys { get; set; }
        public virtual DbSet<tbCategoriaProducto> tbCategoriaProducto { get; set; }
        public virtual DbSet<tbCategoriaRequerimiento> tbCategoriaRequerimiento { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbCompras> tbCompras { get; set; }
        public virtual DbSet<tbDetalleCompras> tbDetalleCompras { get; set; }
        public virtual DbSet<tbDetalleDocumento> tbDetalleDocumento { get; set; }
        public virtual DbSet<tbDetalleDocumentoPendiente> tbDetalleDocumentoPendiente { get; set; }
        public virtual DbSet<tbDetalleOrdenCompra> tbDetalleOrdenCompra { get; set; }
        public virtual DbSet<tbDistrito> tbDistrito { get; set; }
        public virtual DbSet<tbDocumento> tbDocumento { get; set; }
        public virtual DbSet<tbDocumentosPendiente> tbDocumentosPendiente { get; set; }
        public virtual DbSet<tbEmpleado> tbEmpleado { get; set; }
        public virtual DbSet<tbEmpresa> tbEmpresa { get; set; }
        public virtual DbSet<tbEmpresaActividades> tbEmpresaActividades { get; set; }
        public virtual DbSet<tbExoneraciones> tbExoneraciones { get; set; }
        public virtual DbSet<tbImpuestos> tbImpuestos { get; set; }
        public virtual DbSet<tbInventario> tbInventario { get; set; }
        public virtual DbSet<tbMovimientos> tbMovimientos { get; set; }
        public virtual DbSet<tbOrdenCompra> tbOrdenCompra { get; set; }
        public virtual DbSet<tbPagos> tbPagos { get; set; }
        public virtual DbSet<tbParametrosEmpresa> tbParametrosEmpresa { get; set; }
        public virtual DbSet<tbPersona> tbPersona { get; set; }
        public virtual DbSet<tbProducto> tbProducto { get; set; }
        public virtual DbSet<tbPromociones> tbPromociones { get; set; }
        public virtual DbSet<tbProveedores> tbProveedores { get; set; }
        public virtual DbSet<tbProvincia> tbProvincia { get; set; }
        public virtual DbSet<tbReporteHacienda> tbReporteHacienda { get; set; }
        public virtual DbSet<tbRequerimientos> tbRequerimientos { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbTipoClientes> tbTipoClientes { get; set; }
        public virtual DbSet<tbTipoDocumento> tbTipoDocumento { get; set; }
        public virtual DbSet<tbTipoId> tbTipoId { get; set; }
        public virtual DbSet<tbTipoMedidas> tbTipoMedidas { get; set; }
        public virtual DbSet<tbTipoMoneda> tbTipoMoneda { get; set; }
        public virtual DbSet<tbTipoMovimiento> tbTipoMovimiento { get; set; }
        public virtual DbSet<tbTipoPago> tbTipoPago { get; set; }
        public virtual DbSet<tbTipoPuesto> tbTipoPuesto { get; set; }
        public virtual DbSet<tbTipoVenta> tbTipoVenta { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbCategoria2Cabys> tbCategoria2Cabys { get; set; }
        public virtual DbSet<tbCategoria3Cabys> tbCategoria3Cabys { get; set; }
        public virtual DbSet<tbCategoria4Cabys> tbCategoria4Cabys { get; set; }
        public virtual DbSet<tbCategoria5Cabys> tbCategoria5Cabys { get; set; }
        public virtual DbSet<tbCategoria6Cabys> tbCategoria6Cabys { get; set; }
        public virtual DbSet<tbPersonasTribunalS> tbPersonasTribunalS { get; set; }
    }
}
